### PR TITLE
Reviewer, please read the top of README file

### PR DESCRIPTION
**Pull request by Bogdan11p**

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for sending your project for review - I really like it, especially your jsx markup and form validation. I left several comments below and hope they can help with improving your project and getting more points. Good luck!✨

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Incorrect fonts are rendered on all pages, you need to make sure that all necessary font-faces are added to the project and link correctly using `@font-face` rules with correct imports
    * Incorrect `border-radius` of the login button in header section
    * Incorrect spaces between items inside header navbar and footer sections
    * Incorrecr text properties of header tabs and buttons on 768 viewport
    * Incorrect height of the navbar on 320 viewport
    * Mobile navigation block looks incorrectly on 320 viewport (incorrect height and spaces between items, close button shouldn't have white background, and the rest of the page should have dark overlay)
    * Footer section doesn't match the design on 320 viewport
    * Incorrect vertical spaces of "search results" title on all screen resolutions
    * All big text inside news card should be ended with ellipsis
    * Incorrect line-height of the `card__title` on 768 viewport
    * Incorrect vertical spaces of the show more button on 768, 320 viewports
    * Incorrect text properties of the "search results" title on 320 viewport
    * You need to check and fix all text properties and gaps between all items inside `header__profile` on all screen resolutions
    * Modal window looks incorrectly on 320 viewport (incorrect height, bottom borders shouldn't be rounded, incorrect spaces between items)
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * page content should not stretch on screen resolutions greater than 1440px
    * Mobile nav menu should stretch and be centered on intermediate screen resolutions
    * Home page scrolls and breaks on 321px - 500px screen resolutions and `saved-news` page scrolls on 321px - 570px screen resolutions
    * All sections and its content should be centered horizontally on intermediate screen resolutions
    * The home page scrolls horizontally on 769px - 850px when the page shows search results
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * Footer links don't work
- [x]  Classes are named according to BEM specifications.
    * You can't use BEM element class outside of its block, BEM element is a non-separate part which can be used only as part of its block. Please check and fix all similar cases throughout the project
    * Please don't use capital letters and spaces in class names **throughout the project**
    * Header navbar burger should be a button, not an image
    * `search__form_button` should be a BEM element, not a BEM modifier
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * Please use `section` tag for `search` block
    * You need to use `footer` tag for the footer instead of `section`
    * There should be only one `h1` tag on each page
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Header active tab should have underline (if I'm on home page - home tab should have underline. It works only when the user is logged in but should work even if the user isn't logged in)
    * Incorrect background color of `modal__submit-valid`
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * Not all `font-family` styles have alternative fonts
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 50

## Additional comments:

    - Your README.md file markup looks broken in github repository (it looks great in project folder, but it's a description of the project, so it will be great to make it look good on github site too)
    - Note, that [object object] is displayed instead of username on login/logout button and on `saved-news` page when the user is logged in

**Comment by FiLLa-FaS** [comment]
Hi! Thanks for the corrections, your project looks better. I marked several issues below, you need to fix them to get more points and improve your project. Good luck!✨

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Incorrect font is rendered on all pages, you need to make sure that all necessary font-faces are added to the project and link correctly using `@font-face` rules with correct imports
    * Incorrect spaces between items inside header navbar and footer sections
    * Incorrect text properties of header buttons on 768 viewport
    * `card__title` text shouldn't be cropped vertically on all screen resolutions https://pasteboard.co/aE2GacIOvTIG.png
    * Incorrect width and vertical spaces of `search__button` on 320 viewport
    * Modal window looks incorrectly on 320 viewport  (first screenshot - mockup https://pasteboard.co/wh18NxXvA6hO.png, second screenshot - your project https://pasteboard.co/x8Y7KGLv5BPq.png
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * Page content should be centered horizontally on more than 1440px screen resolutions
    * The page scrolls horizontally on 321px - 1456px screen resolutions (for both pages)
    * Mobile nav menu should stretch and be centered on intermediate screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * You can't use BEM element class outside of its block, BEM element is a non-separate part which can be used only as part of its block. You can see the example on the screenshot https://pasteboard.co/KJWgtwilR5q9.png, but you should check and fix all similar cases throughout the project
    * Please don't use capital letters and spaces in class names throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * Please use `section` tag for `search` block
    * There should be only one `h1` tag on each page
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Incorrect background color of `modal__submit-valid`
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
    * Not all font-family styles have alternative fonts - you need to add them
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 62

**Comment by Bogdan11p** [comment]
I cannot find where I have two h1 tags in one page, I searched for it and I cannot seem to find two h1 tags on one page

**Comment by FiLLa-FaS** [comment]
Home page has two `h1` tags and `saved-articles` page has no `h1` tags at all https://pasteboard.co/ibm6Lfmi1v0X.png

**Comment by Bogdan11p** [comment]
> Home page has two `h1` tags and `saved-articles` page has no `h1` tags at all https://pasteboard.co/ibm6Lfmi1v0X.png

Thank you I fixed it, however I pushed my new code here but it is not ready for review yet because I am not able to search articles anymore. I wanted to ask if you could look at it and see why I am not able to search for articles anymore even though I did not change anything for it.

**Comment by FiLLa-FaS** [comment]
It looks like the api just returns empty results on any request, but I'm not sure why. I guess it will be more effective to ask the tutors, maybe there's some kind of a server error

**Comment by FiLLa-FaS** [comment]
Hi! Your project is almost finished, it's great to see that both pages look so similar with the mockup. I marked the rest issues below, keep up the good work!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * header section looks incorrectly on 768 viewport - please check width of all items and spaces between them
    * Incorrect width of the news card on 320 viewport
    * Big space between `about__left-picture` and `about__right-title` on 320 viewport
    * Modal window looks incorrectly on 320 viewport (first screenshot - mockup https://pasteboard.co/wh18NxXvA6hO.png, second screenshot - your project https://pasteboard.co/x8Y7KGLv5BPq.png
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The page shouldn't stretch on more than 1440px screen resolutions - it should keep its width and center horizontally
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * You can't use BEM element class outside of its block, BEM element is a non-separate part which can be used only as part of its block. You should check and fix all similar cases throughout the project
    * Please don't use capital letters and spaces in class names throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * Each `font-family` style should contain at least 2 values - our first main font and generic font-family as the last value. You can also add alternative font-family values between these two values to control your items better
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 69

**Comment by FiLLa-FaS** [comment]
Hi! You've got more than 80 points, so I'm glad to accept your project! You still can fix the rest issues, but now you can move on to the next stage. Good luck!🚀

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * `header` section looks incorrectly on 768 viewport - please check width of all items and spaces between them https://pasteboard.co/vexW8K5kpg2n.png
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * You can't use BEM element class outside of its block, BEM element is a non-separate part which can be used only as part of its block. You should check and fix all similar cases throughout the project
    * Please don't use capital letters and spaces in class names throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 83

**Pull request merged**
